name: medical-coding-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - streamlit=0.86.0
  - pillow=8.3.1
  - fpdf=1.7.2
  - openai=0.27.1
  - pypdf2=1.26.0
  - reportlab=3.6.1
